### ISSUE TITLE
GRKFirebaseProvider cuts off user properties by one character

### ISSUE THREAD

**Issue by jpetrich** [levigroker/GRKAnalytics#3]
On line 236 of GRKFirebaseProvider, cropString removes the last character unintentionally:

`		retVal = [retVal substringToIndex:MIN(retVal.length, maxLength) - 1];
`

[According to Apple's documentation](https://developer.apple.com/documentation/foundation/nsstring/1408017-substringtoindex), substringToIndex is exclusive of the end index, so the -1 is unnecessary.

**Comment by jpetrich** [comment]
#4

**Comment by levigroker** [comment]
Much appreciated.
